services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: wallet-api-app
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: walletdb
      DB_USERNAME: wallet_user
      DB_PASSWORD: wallet_pass
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:17-alpine
    container_name: wallet-api-postgres
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: wallet-api-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgres_data:
